### ISSUE TITLE
Binder not working: "MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'."

### ISSUE THREAD

**Issue by asmith26** [davidbrochart/xtrude#3]
Hi there,

I'm trying to run the example notebook in binder, but unfortunately is doesn't seem to display the surface/terrain, only the map in the background:

![image](https://user-images.githubusercontent.com/6988036/144869538-9f417b34-3c41-45e9-bc59-43938ab22758.png)

Here is the output of `debug_output`:

<details>

<summary>Binder Stack trace</summary>

```python
debug_output = Output()

debug_output

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in terrain_handler(self, request)
    153 
    154             data = self.get_tile(x, y, z)
--> 155             data = (data + self.offset) * self.factor
    156             rgb = np.empty((self.tile_width, self.tile_width, 3), dtype=np.uint8)
    157             rgb[:, :, 2] = data % 256

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in terrain_handler(self, request)
    153 
    154             data = self.get_tile(x, y, z)
--> 155             data = (data + self.offset) * self.factor
    156             rgb = np.empty((self.tile_width, self.tile_width, 3), dtype=np.uint8)
    157             rgb[:, :, 2] = data % 256

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in surface_handler(self, request)
    138             if self.vmax is None:
    139                 self.vmax = self.da.max().values
--> 140             data = (self.get_tile(x, y, z) - self.vmin) / (self.vmax - self.vmin)
    141             rgb = self.colormap(data)[:, :, :3] * 255
    142             image = Image.fromarray(rgb.astype(np.uint8))

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in surface_handler(self, request)
    138             if self.vmax is None:
    139                 self.vmax = self.da.max().values
--> 140             data = (self.get_tile(x, y, z) - self.vmin) / (self.vmax - self.vmin)
    141             rgb = self.colormap(data)[:, :, :3] * 255
    142             image = Image.fromarray(rgb.astype(np.uint8))

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in terrain_handler(self, request)
    153 
    154             data = self.get_tile(x, y, z)
--> 155             data = (data + self.offset) * self.factor
    156             rgb = np.empty((self.tile_width, self.tile_width, 3), dtype=np.uint8)
    157             rgb[:, :, 2] = data % 256

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in surface_handler(self, request)
    138             if self.vmax is None:
    139                 self.vmax = self.da.max().values
--> 140             data = (self.get_tile(x, y, z) - self.vmin) / (self.vmax - self.vmin)
    141             rgb = self.colormap(data)[:, :, :3] * 255
    142             image = Image.fromarray(rgb.astype(np.uint8))

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in terrain_handler(self, request)
    153 
    154             data = self.get_tile(x, y, z)
--> 155             data = (data + self.offset) * self.factor
    156             rgb = np.empty((self.tile_width, self.tile_width, 3), dtype=np.uint8)
    157             rgb[:, :, 2] = data % 256

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in surface_handler(self, request)
    138             if self.vmax is None:
    139                 self.vmax = self.da.max().values
--> 140             data = (self.get_tile(x, y, z) - self.vmin) / (self.vmax - self.vmin)
    141             rgb = self.colormap(data)[:, :, :3] * 255
    142             image = Image.fromarray(rgb.astype(np.uint8))

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in terrain_handler(self, request)
    153 
    154             data = self.get_tile(x, y, z)
--> 155             data = (data + self.offset) * self.factor
    156             rgb = np.empty((self.tile_width, self.tile_width, 3), dtype=np.uint8)
    157             rgb[:, :, 2] = data % 256

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in surface_handler(self, request)
    138             if self.vmax is None:
    139                 self.vmax = self.da.max().values
--> 140             data = (self.get_tile(x, y, z) - self.vmin) / (self.vmax - self.vmin)
    141             rgb = self.colormap(data)[:, :, :3] * 255
    142             image = Image.fromarray(rgb.astype(np.uint8))

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in terrain_handler(self, request)
    153 
    154             data = self.get_tile(x, y, z)
--> 155             data = (data + self.offset) * self.factor
    156             rgb = np.empty((self.tile_width, self.tile_width, 3), dtype=np.uint8)
    157             rgb[:, :, 2] = data % 256

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

---------------------------------------------------------------------------
MissingCRS                                Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in get_tile(self, x, y, z)
    185                 da_tile = self.da.sel(y=slice(bounds.north + self.dy, bounds.south - self.dy), x=slice(bounds.west - self.dx, bounds.east + self.dx))
    186                 da_tile = coarsen(da_tile, self.tile_width)
--> 187                 data = reproject(da_tile, xy_bounds.left, xy_bounds.top, x_pix, y_pix, self.tile_width)
    188                 self.tiles[key] = data
    189             return self.tiles[key]

/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in reproject(source, x0, y0, x_res, y_res, tile_width)
    226     f = y0
    227     dst_affine = Affine(a, b, c, d, e, f)
--> 228     destination = source.rio.reproject('EPSG:3857', transform=dst_affine, shape=(tile_width, tile_width), resampling=Resampling.bilinear)
    229     return destination.values
    230 

/srv/conda/envs/notebook/lib/python3.7/site-packages/rioxarray/raster_array.py in reproject(self, dst_crs, resolution, shape, transform, resampling, nodata, **kwargs)
    391         if self.crs is None:
    392             raise MissingCRS(
--> 393                 "CRS not found. Please set the CRS with 'rio.write_crs()'."
    394                 f"{_get_data_var_message(self._obj)}"
    395             )

MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/xtrude/xtrude.py in surface_handler(self, request)
    138             if self.vmax is None:
    139                 self.vmax = self.da.max().values
--> 140             data = (self.get_tile(x, y, z) - self.vmin) / (self.vmax - self.vmin)
    141             rgb = self.colormap(data)[:, :, :3] * 255
    142             image = Image.fromarray(rgb.astype(np.uint8))

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```
</details>

Thanks for any help ([again](https://github.com/davidbrochart/xtrude/issues/2))! :)

**Comment by davidbrochart** [comment]
Hi @asmith26, are you using JupyterLab? It seems that [JupyterLab 3 is still not supported in pydeck](https://github.com/visgl/deck.gl/issues/5615).

**Comment by asmith26** [comment]
Hi @davidbrochart, Thanks for the very quick response and for your help! :)

I'm using the [Binder link in the README](https://mybinder.org/v2/gh/davidbrochart/xtrude/main?filepath=examples%2Fintroduction.ipynb), which uses Jupyter notebook.

**Comment by davidbrochart** [comment]
It looks like we now have to add:
```python
da.rio.write_crs("epsg:4326", inplace=True)
```
I didn't investigate further, but it's probably a change in rioxarray.
Do you want to update the example notebook?

**Comment by asmith26** [comment]
Thanks very much for the info, can confirm that change fixes my problem. Thanks again!

**Comment by mnoyola** [comment]
Hi, I am having the same problem when running w2w in ubuntu as follows

LCZ class labels renamed from 1 to 17
Traceback (most recent call last):
  File "/home/meteotech/anaconda3/bin/w2w", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/meteotech/anaconda3/lib/python3.11/site-packages/w2w/w2w.py", line 171, in main
    check_lcz_integrity(
  File "/home/meteotech/anaconda3/lib/python3.11/site-packages/w2w/w2w.py", line 414, in check_lcz_integrity
    lcz = lcz.rio.reproject('EPSG:4326')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meteotech/anaconda3/lib/python3.11/site-packages/rioxarray/raster_array.py", line 431, in reproject
    raise MissingCRS(
rioxarray.exceptions.MissingCRS: CRS not found. Please set the CRS with 'rio.write_crs()'.

where did you add the next line?
da.rio.write_crs("epsg:4326", inplace=True) 

help please, thanks in advance
